theme: jekyll-theme-architect
title: [GSoC-Eclipse Che-2020]
description: [This repository aims to explain the work done under the Google Summer of Code project with Eclipse Che in 2020]
show_downloads: ["true"]
github:
  zip_url: https://github.com/che-incubator/vscode-teletype-guest/raw/electron-webrtc-patched/vscode-teletype-0.0.1.vsix
  repository_url: https://github.com/che-incubator/vscode-teletype-guest
  tar_url: https://github.com/Rijul5/GSoC-Eclipse-Che-2020

